travis:
  secure:
    BINSTAR_TOKEN: lbGoTluvrGwDHiQdKxAagEyQuDgrFCVSVbqb70hi76QY0hEb0Joic8KpBmLcDdrLmGGWSvHB3t4U9zMtahNMX6wCZDcbQbRWLtbqOXP2ktsqz5vF15QphYI7qK/u4U6333yQW63IiKIajNrk6fVJdL+ns3LkmIU7aqIxMrFoe62xYlKeJLv/HhbL76Mrd6PhdudIbAFTR8XKTpgNhGK8BPAfjQxnncuUHSBbY1dhEhk2iXjo4R8zJuyVk/CtY3dLnmY1QCMINGTNBfMBl5P1SaaiRwl6CTgu1LeO1i+QHdRY7ys7DwGN7XDFsz7u25ZGK0Y0T2RmAjP9u9pe9fnz88qxfB/9bMX7QNNkHaUt5D8P+SO3MKMvHzHUBsIJi1DDq9M3llVGB9znv20TGXdhnN+B1QlgsC2euNS3ohkbcYPdyxqeee3EVqWp/FGPZIeHJ5Eiu5uOUEDW8rxOHl+aS6lVVtfnDHD/tP8IRO6UGyW5g9ShXyZdRXHIiXMeuX4VeRd9Ov3LI3rFP1RQCfqo6WZck7yeCW5f1gQHBj0S/SatmW4qk08K30/sNuCd8udNhJn4VZxrEutfZAG2k9154VYpgPUJGzILnyNcaJEXIBrgwJk8NBFMPbb8oAnIUFgf798viGpY7eMJ3O9dfr0k9jRqtnQbrevlFcmFBt3rv5c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
